

name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Change this to your default branch if necessary

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setting up working directory
        run: echo "Working directory"
        working-directory: ./Docker

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Your Docker Hub username
          password: ${{ secrets.DOCKER_PASSWORD }}  # Your Docker Hub password

      - name: Build Docker image
        run: docker build . -t ${{ secrets.DOCKER_USERNAME }}/dhruv-py:latest

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/dhruv-py:latest