name: Build, Push, and Deploy to Azure

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

env:
  AZURE_CONTAINER_REGISTRY: "dcregistry123.azurecr.io"  # Replace with your ACR login server name

jobs:
  build-and-push:
    defaults:
      run:
        working-directory: ./Docker

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}  # Set up this secret in GitHub Secrets

      - name: Log in to Azure Container Registry (ACR)
        run: az acr login --name dcregistry123

      - name: Build Docker image
        run: |
          docker build -t $AZURE_CONTAINER_REGISTRY/my-app:${{ github.sha }} .
          docker tag $AZURE_CONTAINER_REGISTRY/my-app:${{ github.sha }} $AZURE_CONTAINER_REGISTRY/my-app:latest

      - name: Push Docker image to ACR
        run: |
          docker push $AZURE_CONTAINER_REGISTRY/my-app:${{ github.sha }}
          docker push $AZURE_CONTAINER_REGISTRY/my-app:latest

  deploy-to-aks:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get AKS credentials
        run: az aks get-credentials --resource-group github-actions --name trial-cluster

      - name: Deploy to AKS
        run: |
          kubectl create deployment my-app --image=$AZURE_CONTAINER_REGISTRY/my-app:${{ github.sha }}
          kubectl expose deployment my-app --port=5000 --target-port=5000 --type=LoadBalancer







