name: "Hello world workflow"

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:  # Added colon for consistency

jobs: 
  hello: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3  # Updated to the latest version
      - name: hello-world
        run: ls -altr
        shell: bash

  goodbye: 
    runs-on: ubuntu-latest
    steps: 
      - name: goodbye-world
        run: echo "Goodbye world"
        shell: bash
